SongInfo = {
    ['6000'] = { 'Look To Windward', 'Sleep Token' },
    ['6001'] = { 'Emergence', 'Sleep Token' },
    ['6002'] = { 'Past Self', 'Sleep Token' },
    ['6003'] = { 'Dangerous', 'Sleep Token' },
    ['6004'] = { 'Caramel', 'Sleep Token' },
    ['6005'] = { 'Even In Arcadia', 'Sleep Token' },
    ['6006'] = { 'Provider', 'Sleep Token' },
    ['6007'] = { 'Damocles', 'Sleep Token' },
    ['6008'] = { 'Gethsemane', 'Sleep Token' },
    ['6009'] = { 'Infinite Baths', 'Sleep Token' },
    ['6010'] = { 'Bad Habits', 'KUURO' },
    ['6011'] = { 'Empty Bed', 'Saint Punk' },
    ['6012'] = { 'Big Bands', 'Lil Cap, P Money' },
    ['6013'] = { 'Nightshift', 'Charlotte Plank' },
}